repositories:
  - name: otel
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jaeger
    url: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts

templates:
  global: &global
    namespace: otel
    installed: true
    wait: true
    createNamespace: true
    missingFileHandler: Error
    cleanupOnFail: true

releases:
  - name: otel-operator
    <<: *global
    chart: otel/opentelemetry-operator
    version: 0.76.0
    values:
      - ./opentelemetry-operator/base/values.yaml

  - name: jaeger-aio
    <<: *global
    chart: jaeger/jaeger-all-in-one
    version: 0.1.12
    values:
      - ./jaeger-aio/base/values.yaml

  # - name: tempo
  #   <<: *global
  #   chart: bitnami/grafana-tempo
  #   values:
  #     - grafana-tempo/base/values.yaml

helmDefaults:
  historyMax: 3
  reuseValues: false
  kubeContext: otel-scratch
