fullnameOverride: "otel-op"

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-k8s
  createRbacPermissions: true

admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
